org: ruchir
app: serverless-node-app-demo
service: serverless-node-app-demo

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
