service: ServerlessNodeDemoService

frameworkVersion: ">=1.13.0 <2.0.0"

plugins:
   - serverless-step-functions
   - serverless-step-functions-offline

provider:
  name: aws
  runtime: nodejs12.x
  cfLogs: true
  region: ap-south-1
  memorySize: 128
  timeout: 3
